package io.github.georgerng;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferInt;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

public class Main {
    public static FileWriter output = null;
    public static final Map<Integer,String> colors = new HashMap<>();

    public static void main(String[] args) throws IOException {
        colors.put(0,"0");
        colors.put(1,"8");
        colors.put(2,"7");
        colors.put(3,"F");

        File out = new File("./main.mcfunction");
        out.createNewFile();
        output = new FileWriter(out);
        output.write("""
                ##
                 # main.builder.mcfunction
                 # badapple
                 #
                 # Created by GeorgeRNG.
                 #
                 # This file is autogenerated.
                ##
                
                """);

        int nameLen = 3;
        int frames = Integer.parseInt(args[0]);

        for (int i = frames - 1; i >= 0; i-= 1) {
            try {
                parseFrame(new File("./frames/frame" + padLeft(String.valueOf(i + 1), nameLen) + ".bmp"),i);
                if(i % 10 == 0) System.out.println(100 * (frames - i) / frames);
            }
            catch (Exception e) {
                System.out.println("Frame" + i + ": " + e.getMessage());
            }
        }

        output.close();
    }

    private static void parseFrame(File file, int index) throws IOException {
        BufferedImage original = ImageIO.read(file);
        BufferedImage image = new BufferedImage(original.getWidth(), original.getHeight(), BufferedImage.TYPE_INT_RGB);

        Graphics2D g = image.createGraphics();
        g.drawImage(original, 0, 0, original.getWidth(), original.getHeight(), null);
        g.dispose();

        int[] data = ((DataBufferInt) image.getRaster().getDataBuffer()).getData();

        StringBuilder command = new StringBuilder("execute as @e[type=minecraft:text_display,tag=badapple,tag=");
        command.append(index);
        command.append("] run data merge entity @s {Tags:[\"badapple\",\"");
        command.append(index + 1);
        command.append("\"],text:\"\\\"");

        String lastColor = null;
        int lineI = 0;
        int pixelI = 0;
        int width = image.getWidth(); // chunk size to divide
        for(int i = 0; i < data.length; i += width){
            lineI++;
            if(lineI % 2 != 0) {
                int[] line = Arrays.copyOfRange(data, i, i+width);
                for (int pixel: line) {
                    pixelI++;
                    if(pixelI % 2 != 0) {
                        String color = colors.get((pixel & 0xFF) / 64);
                        if(!Objects.equals(lastColor, color)) {
                            command.append("§");
                            command.append(color);
                            lastColor = color;
                        }
                        command.append("█");
                    }
                }
                command.append("\\\\n");
                lastColor = null;
            }
        }
        command.replace(command.length() - 3,command.length(),"");
        command.append("\\\"\"}\n");
        output.write(command.toString());
    }

    private static String padLeft(String number, int zeros) {
        try {
            return "0".repeat(Math.max(0, zeros)).substring(number.length()) + number;
        } catch (Exception ignored) {
            return number;
        }
    }
}